version: '3'
 
 services:
   web:
     image: php:7.3-apache
     container-name: phpframework
      depends_on:
         - db
        ports:
          - 80:80
    
    db-master:
      image: danieldent/postgres-replication
       restart: always
       environment:
       POSTGRES_PASSWORD: password
        ports:
         - 5432:5432
     
     db-slave:
         image: danieldent/postgres-replication
         restart: always
         environment:
           POSTGRES_PASSWORD: password
           REPLICATE_FROM: db-master
           ports:
            - 5432:5432
            
           links:
            - db-master
         
